"""add logistica fields to PontoRetirada and create TaxaEntrega

Revision ID: 19a0a36fbcd0
Revises: 4f02ec63a4ea
Create Date: 2025-11-30 12:03:41.299108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a0a36fbcd0'
down_revision = '4f02ec63a4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxas_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('prazo_dias', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pontos_retirada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('horario_abertura', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('horario_fechamento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.drop_column('horarios')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos_retirada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horarios', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('ativo')
        batch_op.drop_column('horario_fechamento')
        batch_op.drop_column('horario_abertura')
        batch_op.drop_column('cep')
        batch_op.drop_column('cidade')

    op.drop_table('taxas_entrega')
    # ### end Alembic commands ###
