"""add pedido logistics fields (entrega_tipo, ponto_retirada_id, taxa_entrega_id, valor_frete)

Revision ID: 41ca0e40cdea
Revises: 19a0a36fbcd0
Create Date: 2025-11-30 12:54:12.147795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ca0e40cdea'
down_revision = '19a0a36fbcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ponto_retirada_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('taxa_entrega_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_frete', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_pedidos_taxa_entrega', 'taxas_entrega', ['taxa_entrega_id'], ['id'])
        batch_op.create_foreign_key('fk_pedidos_ponto_retirada', 'pontos_retirada', ['ponto_retirada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedidos_ponto_retirada', type_='foreignkey')
        batch_op.drop_constraint('fk_pedidos_taxa_entrega', type_='foreignkey')
        batch_op.drop_column('valor_frete')
        batch_op.drop_column('taxa_entrega_id')
        batch_op.drop_column('ponto_retirada_id')
        batch_op.drop_column('entrega_tipo')

    # ### end Alembic commands ###
