"""add review and pedido cancelamento fields

Revision ID: 4f02ec63a4ea
Revises: a454e9bbcca3
Create Date: 2025-11-30 11:32:23.406041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f02ec63a4ea'
down_revision = 'a454e9bbcca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'produto_id', name='uix_cliente_produto_review')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cancelamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelado_por', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('cancelado_por')
        batch_op.drop_column('motivo_cancelamento')
        batch_op.drop_column('data_cancelamento')

    op.drop_table('reviews')
    # ### end Alembic commands ###
