"""Add blog models and producer photo upload

Revision ID: 5d99f288a5b0
Revises: 41ca0e40cdea
Create Date: 2025-11-30 15:00:35.785815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d99f288a5b0'
down_revision = '41ca0e40cdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('resumo', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('imagem_capa', sa.String(length=300), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comentarios_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts_blog.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios_blog')
    op.drop_table('posts_blog')
    # ### end Alembic commands ###
