"""add categoria minima columns

Revision ID: a454e9bbcca3
Revises: d76dfe5ac973
Create Date: 2025-11-30 10:26:28.948486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a454e9bbcca3'
down_revision = 'd76dfe5ac973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_minimo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_minima', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('quantidade_minima')
        batch_op.drop_column('valor_minimo')

    # ### end Alembic commands ###
