"""Adiciona campos de pagamento ao modelo Pedido

Revision ID: bca70e0f4357
Revises: 7634413bfc4c
Create Date: 2025-12-03 11:31:14.750850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca70e0f4357'
down_revision = '7634413bfc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagamento_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_pagamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiracao_pagamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_rejeicao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_cartao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ultimos_4_cartao', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('bandeira_cartao', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('bandeira_cartao')
        batch_op.drop_column('ultimos_4_cartao')
        batch_op.drop_column('token_cartao')
        batch_op.drop_column('motivo_rejeicao')
        batch_op.drop_column('expiracao_pagamento')
        batch_op.drop_column('data_pagamento')
        batch_op.drop_column('status_pagamento')
        batch_op.drop_column('pagamento_id')

    # ### end Alembic commands ###
