"""initial schema

Revision ID: d76dfe5ac973
Revises: 
Create Date: 2025-11-30 10:23:09.636470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76dfe5ac973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('categoria')
    op.drop_table('usuario')
    op.drop_table('ponto_retirada')
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    op.drop_table('cliente')
    op.drop_table('produtor')
    op.drop_table('endereco')
    op.drop_table('produto')
    op.drop_table('notificacao')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('origem', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('informacoes_nutricionais', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preco_promocional', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sazonal_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sazonal_fim', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('sazonal_fim')
        batch_op.drop_column('sazonal_inicio')
        batch_op.drop_column('preco_promocional')
        batch_op.drop_column('informacoes_nutricionais')
        batch_op.drop_column('origem')
        batch_op.drop_column('subcategoria')

    op.create_table('notificacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('mensagem', sa.VARCHAR(length=255), nullable=False),
    sa.Column('lida', sa.BOOLEAN(), nullable=True),
    sa.Column('criada_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.Column('unidade', sa.VARCHAR(length=10), nullable=False),
    sa.Column('produtor_id', sa.INTEGER(), nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), nullable=True),
    sa.Column('estoque', sa.INTEGER(), nullable=True),
    sa.Column('imagens', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('apelido', sa.VARCHAR(length=50), nullable=True),
    sa.Column('logradouro', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=2), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=10), nullable=False),
    sa.Column('principal', sa.BOOLEAN(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('certificacoes', sa.VARCHAR(length=200), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('fotos', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('enderecos', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('forma_pagamento', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tipo_recebimento', sa.VARCHAR(length=30), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('data_agendada', sa.DATETIME(), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto_retirada',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dias_funcionamento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('horarios', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('tipo_usuario', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('icone', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'produto_id', name=op.f('uix_cliente_produto'))
    )
    # ### end Alembic commands ###
